services:
  api:
    build: .
    container_name: api-todo-list
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: todoapp
      PORT: 3000
    depends_on:
      - mongo
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - backend

  mongo:
    image: mongo:6
    container_name: mongodb-todo-list
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

volumes:
  mongo-data:
    driver: local

networks:
  backend:
    name: todo-network